{"headline": "Tips for easing the service burden on scientists from underrepresented groups", "tags": ["Read more Letters to Young Scientists", "Letters to Young Scientists", "Column", "Non-disciplinary"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/neil-lewis-jr\">Neil A. Lewis, Jr.</a>, <a href=\"/author/jay-j-van-bavel\">Jay J. Van Bavel </a>, <a href=\"/author/leah-h-somerville\">Leah H. Somerville</a><time>Oct. 22, 2019 , 5:15 PM</time></p>"}
{"headline": "How our daughter\u2019s diagnosis shifted the course of our careers", "tags": ["Read more Working Life", "Working Life", "Non-disciplinary"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/j-andrew-dewoody-0\">J. Andrew DeWoody</a>, <a href=\"/author/yssa-d-dewoody\">Yssa D. DeWoody</a><time>Oct. 24, 2019 , 2:00 PM</time></p>"}
{"headline": "Why scientists should take more coffee breaks", "tags": ["Read more Working Life", "Working Life", "Non-disciplinary"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/vivienne-tam\">Vivienne Tam</a><time>Oct. 31, 2019 , 2:00 PM</time></p>"}
{"headline": "What my mother\u2019s death taught me about grieving professional losses", "tags": ["Read more Your Unicorn Career", "Your Unicorn Career", "Column", "Non-disciplinary"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/alaina-g-levine\">Alaina G. Levine</a><time>Oct. 28, 2019 , 11:00 AM</time></p>"}
{"headline": "Post-Ph.D. job searches are tough. Here\u2019s how I escaped Dr. Seuss\u2019s \u2018Waiting Place\u2019", "tags": ["Read more Working Life", "Working Life", "Non-disciplinary"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/nathan-pickle\">Nathan Pickle</a><time>Oct. 17, 2019 , 2:00 PM</time></p>"}
{"headline": "Community science: Not just a hobby ", "tags": ["Job Market", "Advice", "Graduate", "Postdoc", "Academic"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/chris-tachibana\">Chris Tachibana</a><time>Aug. 30, 2019 , 2:00 PM</time></p>"}
{"headline": "Top employers: Breakthroughs, impact, and purpose", "tags": ["Issues and Perspectives", "Midcareer", "Industry", "Life Sciences"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/chris-tachibana-0\">Chris Tachibana</a><time>Oct. 25, 2019 , 2:00 PM</time></p>"}
{"headline": "For academic parents, work travel can be costly\u2014but some universities are stepping up their support", "tags": ["Career-related Policy", "Non-disciplinary"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/tien-nguyen\">Tien Nguyen</a><time>Sep. 4, 2019 , 2:40 PM</time></p>"}
{"headline": "I wanted to join my fellow Puerto Ricans in protest\u2014but I\u2019m far away for my Ph.D.", "tags": ["Read more Working Life", "Working Life", "Non-disciplinary"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/luis-alexis-rodr-guez-cruz\">Luis Alexis Rodr\u00edguez-Cruz</a><time>Aug. 29, 2019 , 2:00 PM</time></p>"}
{"headline": "As a professor, I wanted to have a bigger impact\u2014so I left academia for a government job", "tags": ["Read more Working Life", "Working Life", "Non-disciplinary"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/gis-le-muller-parker\">Gis\u00e8le Muller-Parker</a><time>Sep. 5, 2019 , 2:00 PM</time></p>"}
{"headline": "How to keep a lab notebook", "tags": ["Read more How-Tos", "How-To", "Advice", "Non-disciplinary"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/elisabeth-pain\">Elisabeth Pain</a><time>Sep. 3, 2019 , 1:45 PM</time></p>"}
{"headline": "U.S. academics, make sure you know the rules about foreign funding and affiliations", "tags": ["Read more Taken for Granted", "Taken for Granted", "Column", "Non-disciplinary"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/beryl-lieff-benderly\">Beryl Lieff Benderly</a><time>Sep. 11, 2019 , 10:40 AM</time></p>"}
{"headline": "How a student\u2019s panic attack changed my approach to teaching", "tags": ["Read more Working Life", "Working Life", "Non-disciplinary"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/roshini-ramachandran\">Roshini Ramachandran</a><time>Sep. 26, 2019 , 2:00 PM</time></p>"}
{"headline": "Universities need to do more to support grad student parents", "tags": ["Read more Working Life", "Working Life", "Non-disciplinary"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/riley-galton\">Riley Galton</a><time>Sep. 12, 2019 , 2:00 PM</time></p>"}
{"headline": "What do we know about Ph.D. scientists\u2019 career paths?", "tags": ["Read more Taken for Granted", "Taken for Granted", "Column", "Non-disciplinary"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/beryl-lieff-benderly\">Beryl Lieff Benderly</a><time>Sep. 30, 2019 , 10:00 AM</time></p>"}
{"headline": "New lab, new adventure: Moving your lab to another country", "tags": ["Advice", "Midcareer", "Academic", "Industry", "Biomedical", "Engineering", "Life Sciences", "Physical Sciences"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/alaina-g-levine\">Alaina G. Levine</a><time>Sep. 13, 2019 , 2:00 PM</time></p>"}
{"headline": "Ph.D. students face significant mental health challenges", "tags": ["Wellness and Health", "Non-disciplinary"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/elisabeth-pain\">Elisabeth Pain</a><time>Apr. 4, 2017 , 3:15 PM</time></p>"}
{"headline": "A guide to diagnosing and treating \u2018Undergraduate Awesomeness\u2019", "tags": ["Read more Experimental Error", "Experimental Error", "Column", "Non-disciplinary"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/adam-ruben\">Adam Ruben</a><time>Sep. 18, 2019 , 1:15 PM</time></p>"}
{"headline": "Three lessons from industry that I\u2019m taking back to academia", "tags": ["Read more Working Life", "Working Life", "Non-disciplinary"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/yumeng-mao\">Yumeng Mao</a><time>Sep. 19, 2019 , 2:00 PM</time></p>"}
{"headline": "Grad students to thesis committees: no more hors d'oeuvres", "tags": ["Read more Experimental Error", "Experimental Error", "Column", "Non-disciplinary"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/adam-ruben\">Adam Ruben</a><time>Oct. 16, 2019 , 3:45 PM</time></p>"}
{"headline": "Help funders help you: Five tips for writing effective funding applications", "tags": ["Read more Letters to Young Scientists", "Letters to Young Scientists", "Column", "Non-disciplinary"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/neil-lewis-jr\">Neil A. Lewis, Jr.</a>, <a href=\"/author/leah-h-somerville\">Leah H. Somerville</a>, <a href=\"/author/jay-j-van-bavel\">Jay J. Van Bavel </a>, <a href=\"/author/william-cunningham\">William A. Cunningham</a><time>Sep. 23, 2019 , 12:00 PM</time></p>"}
{"headline": "Grad student unions dealt blow as proposed new rule says students aren\u2019t \u2018employees\u2019", "tags": ["Career-related Policy", "Non-disciplinary"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/katie-langin\">Katie Langin</a><time>Sep. 20, 2019 , 4:45 PM</time></p>"}
{"headline": "Reviewers, don\u2019t be rude to nonnative English speakers", "tags": ["Read more Working Life", "Working Life", "Non-disciplinary"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/adriana-l-romero-olivares\">Adriana L. Romero-Olivares</a><time>Oct. 3, 2019 , 2:00 PM</time></p>"}
{"headline": "Be proud of your resume, wobbles and all", "tags": ["Read more Career Fables", "Career Fables", "Column", "Non-disciplinary"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/karin-bodewits\">Karin Bodewits</a><time>Oct. 7, 2019 , 10:00 AM</time></p>"}
{"headline": "Alzheimer\u2019s research reset", "tags": ["Advice", "Midcareer", "Academic", "Industry", "Life Sciences"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/kendall-powell\">Kendall Powell</a><time>Oct. 4, 2019 , 2:00 PM</time></p>"}
{"headline": "How I made peace with my imperfections in grad school", "tags": ["Read more Working Life", "Working Life", "Non-disciplinary"], "byline": "<p class=\"byline byline--article\">\n  By <a href=\"/author/brittany-l-uhlorn\">Brittany L. Uhlorn</a><time>Oct. 10, 2019 , 2:00 PM</time></p>"}